 version: "3"
 services:
   server01:
     image: matias/server01
     deploy:
       replicas: 1
       resources:
         limits:
           cpus: "0.1"
           memory: 50M
       restart_policy:
         condition: on-failure
     ports:
       - "3000:3000"
     networks:
       - webnet
   mongo:
     image: mongo
     deploy:
       replicas: 1
       resources:
         limits:
           cpus: "0.1"
           memory: 50M
       restart_policy:
         condition: on-failure
     ports:
       - "27017:27017"
     networks:
       - webnet
 networks:
   webnet:
    driver: "bridge"